# Use Node.js LTS version as base image
FROM node:latest

# Set working directory
WORKDIR /usr/src/app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

#Enable cron
ENV ENABLE_CRON=true

# Environment variables
ENV NODE_ENV=development

# Copy application code
COPY . .

# Expose the port the app runs on
EXPOSE 5000

# Start the application
CMD ["node", "server.js"]