name: Docker Deploy to EC2

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./server          # IMPORTANT: Point to server folder
        file: ./server/Dockerfile  # IMPORTANT: Specify Dockerfile path
        push: true
        tags: rutvikmalaviya0322/hotel-booking-server:latest
        
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull rutvikmalaviya0322/hotel-booking-server:latest
          docker stop hotel-booking-server || true
          docker rm hotel-booking-server || true
          docker run -d --name hotel-booking-server -p 80:3000 rutvikmalaviya0322/hotel-booking-server:latest
